
spring:
  application:
    name: jour3
  profiles:
    active: dev
  devtools:
    restart:
      enabled: true
  thymeleaf:
    enabled: true
    cache: false

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: barb
    password: barb
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect


---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: prod